// Each character has a unique power with cooldown
// powerKey: internal id, powerName: display name, powerDesc: shown on select screen
// cooldown: ms between uses, duration: ms the effect lasts

export const CHARACTERS = {
  neon: [
    { id:'hacker',  name:'HACKER',  icon:'👾', color:0x00f5ff, accent:0xff0080, desc:'Elite coder',
      powerKey:'emp',       powerName:'EMP BLAST',    powerDesc:'Destroys all enemies on screen',      cooldown:12000, duration:0 },
    { id:'cyborg',  name:'CYBORG',  icon:'🤖', color:0x00ff88, accent:0x0088ff, desc:'Half machine',
      powerKey:'overclock', powerName:'OVERCLOCK',    powerDesc:'2× speed boost for 5 seconds',        cooldown:10000, duration:5000 },
    { id:'ninja',   name:'NINJA',   icon:'🥷', color:0x8800ff, accent:0xff00ff, desc:'Shadow runner',
      powerKey:'phase',     powerName:'PHASE',        powerDesc:'Ghost through obstacles for 4s',      cooldown:14000, duration:4000 },
    { id:'punk',    name:'PUNK',    icon:'⚡', color:0xffee00, accent:0xff4400, desc:'Street rebel',
      powerKey:'shock',     powerName:'SHOCKWAVE',    powerDesc:'Stuns all nearby enemies',            cooldown:11000, duration:0 },
    { id:'drone',   name:'DRONE',   icon:'🚁', color:0xff0080, accent:0x00f5ff, desc:'Sky patrol',
      powerKey:'hover',     powerName:'HOVER',        powerDesc:'Slow fall for 5 seconds',             cooldown:10000, duration:5000 },
  ],
  ocean: [
    { id:'diver',   name:'DIVER',   icon:'🤿', color:0x00ccff, accent:0x00ffaa, desc:'Deep explorer',
      powerKey:'sonar',     powerName:'SONAR PULSE',  powerDesc:'Reveals & destroys hidden traps',     cooldown:12000, duration:0 },
    { id:'mermaid', name:'MERMAID', icon:'🧜', color:0x00ffaa, accent:0xff88cc, desc:'Sea creature',
      powerKey:'current',   powerName:'TIDAL CURRENT',powerDesc:'Pulls all coins to you for 6s',       cooldown:9000,  duration:6000 },
    { id:'shark',   name:'SHARK',   icon:'🦈', color:0x4488aa, accent:0xffffff, desc:'Apex predator',
      powerKey:'frenzy',    powerName:'FRENZY',       powerDesc:'Stomp kills give +10 points for 5s',  cooldown:11000, duration:5000 },
    { id:'octopus', name:'OCTOPUS', icon:'🐙', color:0xff44aa, accent:0xaa44ff, desc:'Eight arms',
      powerKey:'ink',       powerName:'INK CLOUD',    powerDesc:'Destroys all obstacles near you',     cooldown:13000, duration:0 },
    { id:'crab',    name:'CRAB',    icon:'🦀', color:0xff4400, accent:0xffaa00, desc:'Shell armor',
      powerKey:'shell',     powerName:'SHELL GUARD',  powerDesc:'Absorbs 2 hits without losing life',  cooldown:15000, duration:8000 },
  ],
  lava: [
    { id:'salamander', name:'SALAMANDER', icon:'🦎', color:0xff6600, accent:0xffaa00, desc:'Fire lizard',
      powerKey:'fireproof', powerName:'FIREPROOF',    powerDesc:'Immune to lava obstacles for 6s',     cooldown:12000, duration:6000 },
    { id:'phoenix',    name:'PHOENIX',    icon:'🔥', color:0xff2200, accent:0xffee00, desc:'Reborn in fire',
      powerKey:'rebirth',   powerName:'REBIRTH',      powerDesc:'Auto revive once without losing life',cooldown:20000, duration:0 },
    { id:'golem',      name:'GOLEM',      icon:'🗿', color:0x884422, accent:0xff6600, desc:'Stone giant',
      powerKey:'quake',     powerName:'EARTHQUAKE',   powerDesc:'Destroys all ground enemies',         cooldown:13000, duration:0 },
    { id:'demon',      name:'DEMON',      icon:'😈', color:0xaa0000, accent:0xff0044, desc:'Underworld lord',
      powerKey:'hellfire',  powerName:'HELLFIRE',     powerDesc:'Burn trail destroys enemies behind',  cooldown:11000, duration:4000 },
    { id:'pyro',       name:'PYRO',       icon:'💥', color:0xffaa00, accent:0xff2200, desc:'Explosion lover',
      powerKey:'blast',     powerName:'MEGA BLAST',   powerDesc:'Huge explosion clears the screen',    cooldown:14000, duration:0 },
  ],
  space: [
    { id:'astronaut', name:'ASTRONAUT', icon:'👨‍🚀', color:0xffffff, accent:0xaaaaff, desc:'Space pioneer',
      powerKey:'jetpack',   powerName:'JETPACK',      powerDesc:'Fly upward freely for 4 seconds',     cooldown:12000, duration:4000 },
    { id:'alien',     name:'ALIEN',     icon:'👽', color:0x44ff88, accent:0x88ffcc, desc:'Extraterrestrial',
      powerKey:'abduct',    powerName:'ABDUCTION',    powerDesc:'Teleport forward 400px instantly',    cooldown:10000, duration:0 },
    { id:'robot',     name:'ROBOT',     icon:'🦾', color:0xaaaaff, accent:0x8844ff, desc:'AI unit',
      powerKey:'shield_bot',powerName:'FORCE FIELD',  powerDesc:'Full shield absorbs 3 hits for 6s',   cooldown:15000, duration:6000 },
    { id:'pilot',     name:'PILOT',     icon:'🚀', color:0xff8844, accent:0xffaa44, desc:'Ace flier',
      powerKey:'afterburn', powerName:'AFTERBURNER',  powerDesc:'3× speed for 3 seconds',              cooldown:11000, duration:3000 },
    { id:'android',   name:'ANDROID',   icon:'🤖', color:0x44aaff, accent:0xffffff, desc:'Humanoid AI',
      powerKey:'scan',      powerName:'THREAT SCAN',  powerDesc:'Freezes all enemies for 4 seconds',   cooldown:13000, duration:4000 },
  ],
  jungle: [
    { id:'explorer', name:'EXPLORER', icon:'🧭', color:0xaaff44, accent:0xffee44, desc:'Treasure hunter',
      powerKey:'treasure',  powerName:'TREASURE MAP', powerDesc:'Doubles all coin value for 6s',       cooldown:11000, duration:6000 },
    { id:'monkey',   name:'MONKEY',   icon:'🐒', color:0xcc8844, accent:0xffaa44, desc:'Tree swinger',
      powerKey:'swing',     powerName:'VINE SWING',   powerDesc:'Launch forward and gain height',       cooldown:9000,  duration:0 },
    { id:'frog',     name:'FROG',     icon:'🐸', color:0x44ff44, accent:0x88ff00, desc:'High jumper',
      powerKey:'superjump', powerName:'SUPER JUMP',   powerDesc:'Massive jump 3× normal height',       cooldown:8000,  duration:0 },
    { id:'panther',  name:'PANTHER',  icon:'🐆', color:0x223322, accent:0xaaff44, desc:'Silent hunter',
      powerKey:'stealth',   powerName:'STEALTH',      powerDesc:'Enemies ignore you for 5 seconds',    cooldown:13000, duration:5000 },
    { id:'shaman',   name:'SHAMAN',   icon:'🪄', color:0xaa44ff, accent:0xffaa44, desc:'Ancient magic',
      powerKey:'totem',     powerName:'SPIRIT TOTEM', powerDesc:'Summons shield + magnet + speed',      cooldown:18000, duration:3000 },
  ],
};
